import fetch from 'node-fetch'
let handler = async (m, { conn }) => {
  let caption =  `
╭─[𝔇𝔢𝔪𝔬𝔫 𝔪𝔡]
 | 
│╭────────────────────
┴│👋 Hey there, ${conn.getName(m.sender)}!
⬡│🤖 I\'m 🐸𝔇𝔢𝔪𝔬𝔫 𝔪𝔡\n⬡│ I\'m up and running! 🚀
│╰────────────────────
┠───[ *BOT INFO* ]────╮
│╭────────────────────
┴│    𝙳𝙴𝙼𝙾𝙽 𝙼𝙳🦇
⬡│💻 A WhatsApp bot created by:
⬡│👨‍💻 𝙲𝙾𝙽𝙵𝚁𝙾𝙽𝚃𝙴𝚁🪓
⬡│📞 For any inquiries, contact:
⬡│📱 wa.me/254796283064
⬡│🙅‍♂️ Don't call the owner or you\'ll be
⬡│ ignored or blocked! 😬
│╰────────────────────
┠───[ *HOW TO USE* ]────⋆
┴│💡 *Some commands you can use:*
⬡│🔸 .menu \n⬡│- Shows a list of available commands
⬡│🔸 .play \n⬡│- Plays a YouTube video or audio.
⬡│🔸 .sticker \n⬡│- Converts an image to a sticker
┬│🔸 .Ai text \n⬡│- Artificial intelligence 
││ https://github.com/confronter
│╰──────────────
╰────────═┅═───────
*Generated by*𝙲𝙾𝙽𝙵𝚁𝙾𝙽𝚃𝙴𝚁🦄
`.trim()
conn.sendMessage(m.chat, { image: {'https://telegra.ph/file/046eb341473a27e87d379.jpg' }, caption: caption, footer: `Follow me on instagram:\n\tinstagram.com/confronter._` }, { quoted: m })
  //m.reply(caption)
}
handler.help = ['alive']
handler.tags = ['bot check']
handler.command = /^(alive|Hi)$/i


export default handler
